# -*- coding: utf-8 -*-
"""MongoDB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYK_HrFtk8fmHmLoGW7buRQMnQmG22A3

#Connect To database using Colab
"""

from pymongo import MongoClient

client=MongoClient('mongodb://Sudarshan_Gouda:Sudu08384225012@test-shard-00-00.bgays.mongodb.net:27017,test-shard-00-01.bgays.mongodb.net:27017,test-shard-00-02.bgays.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-oj31ma-shard-0&authSource=admin&retryWrites=true&w=majority')

"""**To get list of data base**"""

print(client.list_database_names())

"""**To create new dataBase** """

db= client['Sudarshan']

"""**To create new collection** """

collection=db['Book']

collection1=db['Shopping']

"""**To add document in collection**"""

documentOne={'Book':'Papilon','Year':2001,'Rating':4.8}
collection.insert_one(documentOne)

documentmany=[
{ "_id" : 1, "category" : "food", "budget": 400, "spent": 450 },
{ "_id" : 2, "category" : "drinks", "budget": 100, "spent": 150 },
{ "_id" : 3, "category" : "clothes", "budget": 100, "spent": 50 },
{ "_id" : 4, "category" : "misc", "budget": 500, "spent": 300 },
{ "_id" : 5, "category" : "travel", "budget": 200, "spent": 650 }
]

collection1.insert_many(documentmany)

"""**Find Document in Collection**"""

collection.find()

"""To see complete object"""

list(collection.find())

collection1.find({"budget":{'$gt':100}})

list(collection1.find({"budget":{'$gt':100}}))

"""**To Update the documennt**"""

collection1.update({"_id" : 5},{'$set':{"spent":600}})

list(collection1.find())

"""**Count Document**"""

collection1.count_documents({})

"""**Delete Document**"""

collection1.delete_many({'budget': 200})

list(collection1.find())

"""#TASK"""

db2= client['sample_mflix']

for i in Collection3.find({'year':{'$lte':1920}}):
  print(i)

Collection3=db2['movies']

a=[]
for i in Collection3.find({'year':{'$lte':1920}}):
  a.append(i)

a